name: eatery
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  algolia: ^1.1.2
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.1
  intl: ^0.17.0
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/images/EatLogo.svg
    - lib/images/EatForHat1.png

  fonts:
    - family: Righteous
      fonts:
        - asset: lib/fonts/Righteous-Regular.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/images/EatAppLogo1.png"
